ajout block style , javascript et template flashes
RCv20617ma/app pull request #13
Opened 2018-05-15 23:24 UTC by symnoureddine

2018-05-16 21:05 UTC, RCv20617ma requested changes

2018-05-16 21:05 UTC, RCv20617ma commented on app/Resources/views/layout.html.twig
> +            {% include "BenDoctorsBundle:Default:flashes.html.twig" %}
BenDoctorsBundle ?

2018-05-16 21:05 UTC, RCv20617ma commented on app/Resources/views/layout.html.twig
> +{% block javascripts %}
👍

2018-05-16 21:13 UTC, symnoureddine commented on app/Resources/views/layout.html.twig
> +            {% include "BenDoctorsBundle:Default:flashes.html.twig" %}
oui juste copier coller d'un autre fichier 
je vais les changer  :+1:

2018-05-18 10:28 UTC, RCv20617ma commented on app/Resources/FOSUserBundle/views/layout.html.twig
> +    <meta charset="utf-8">
Il manque la balise <title>

2018-05-18 10:28 UTC, RCv20617ma commented on app/Resources/FOSUserBundle/views/layout.html.twig
> +    <link href="{{ asset('vendor/metisMenu/metisMenu.min.css') }}" rel="stylesheet">
On n'aura pas de menu dans cette page, donc il faut supprimer ce css a mon avis

2018-05-18 10:28 UTC, RCv20617ma commented on src/AppBundle/Resources/views/flashes/flashes.html.twig
> +{% if app.session.flashbag.peekAll|length > 0 %}
Je pense que ce template il faut la déplacer vers *app/Resources/views* puisqu'il sera utiliser dans les autres bundles aussi;

2018-05-19 16:37 UTC, RCv20617ma approved these changes

2018-05-20 00:12 UTC, merged