Heritage car maintenance and charge
RCv20617ma/app pull request #33
Opened 2018-06-27 22:58 UTC by symnoureddine

2018-07-07 19:05 UTC, RCv20617ma requested changes

2018-07-07 19:05 UTC, RCv20617ma commented on src/CarBundle/DataFixtures/ORM/car_maintenance.yml
> -    car_maintenance{1..2000}:
faut regarder ca

2018-07-07 19:05 UTC, RCv20617ma commented on src/CarBundle/Entity/Charge.php
> +    public  $libelle;
les charge peuvent être prédéfinis dont il faut prévoir une entity typeCharge comme TypeCarMaintenance a la place de libelle

2018-07-07 19:05 UTC, RCv20617ma commented on src/CarBundle/Form/AbsractChargeType.php
> +}
retour a la ligne

2018-07-07 19:05 UTC, RCv20617ma commented on src/CarBundle/Form/AbsractChargeType.php
> +                'placeholder' => 'Date d\'entretien',
mettre date comme label et sera valide pour le deux(charge ou entretien)

2018-07-07 19:05 UTC, RCv20617ma commented on src/CarBundle/Resources/views/Charge/edit.html.twig
> +    <script src="{{ asset('bundles/car/js/charge_edit.js') }}"></script>
il faut mettre le fichier dans /charge au lieu de /car ?

2018-07-11 21:55 UTC, Abdelali-hiit approved these changes

2018-07-11 22:37 UTC, merged