L'affichage de la liste des clients
RCv20617ma/app pull request #6
Opened 2017-07-29 23:32 UTC by aka-men

2017-07-29 23:53 UTC, RCv20617ma requested changes

2017-07-29 23:53 UTC, RCv20617ma commented on app/Resources/translations/messages.fr.yml
> +reference_gender_.MALE: Masculin
cette traduction il faut la déplacer dans un fichiers de traduction dula bundle concerné

2017-07-29 23:53 UTC, RCv20617ma commented on app/Resources/views/layout.html.twig
> +{% block pluginsJavascript %}{% endblock %}
renommer Javascript en JS c'est plus simple

2017-07-29 23:53 UTC, RCv20617ma commented on src/AppBundle/Controller/AppController.php
> +use CustomerBundle\Entity\PhysicalCustomer;
il faut separer nos uses des autres bundles mets les en bas

2017-07-29 23:53 UTC, RCv20617ma commented on src/CustomerBundle/Entity/AbstractCustomer.php
> +    abstract public function fullName();
getFulleName c'est mieux je pense

2017-07-29 23:53 UTC, RCv20617ma commented on src/CustomerBundle/Entity/AbstractCustomer.php
> +                $mainEmail = $ec->getEmail();
Ajouter une return $mainEmail; juste aprés

2017-07-29 23:53 UTC, RCv20617ma commented on src/CustomerBundle/Entity/AbstractCustomer.php
> +                $mainPhone = $pc->getPhone();
Idem pour return

2017-07-29 23:53 UTC, RCv20617ma commented on src/CustomerBundle/Entity/AbstractCustomer.php
> +        $mainPhone = $this->getPhones()->isEmpty() ? null : $this->getPhones()->first()->getPhone();
cette ligne a deplacer apres la boucle

2017-07-29 23:53 UTC, RCv20617ma commented on src/CustomerBundle/Entity/AbstractCustomer.php
> +        $mainEmail = $this->getEmails()->isEmpty() ? null : $this->getEmails()->first()->getEmail();
deplacer apres la boucle

2017-07-29 23:53 UTC, RCv20617ma commented on src/CustomerBundle/Entity/CustomerEmail.php
> +     * @var ReferenceEmailType
:+1:

2017-07-29 23:53 UTC, RCv20617ma commented on src/CustomerBundle/Entity/CustomerEmail.php
> +    public function isMain()
:+1:

2017-07-29 23:56 UTC, aka-men commented on app/Resources/translations/messages.fr.yml
> +reference_gender_.MALE: Masculin
normalement on va les utiliser dans tous les bundles par exemple list_info pour la liste des voitures,contrat etc, search pour la recherche et le sexe pour un client et employe chaufeur etc

2017-07-29 23:57 UTC, aka-men commented on app/Resources/views/layout.html.twig
> +{% block pluginsJavascript %}{% endblock %}
d'accord,tu as compris d'abord pourquoi j'ai ajouté 2 block JS ??

2017-07-30 00:00 UTC, aka-men commented on src/AppBundle/Controller/AppController.php
> +use CustomerBundle\Entity\PhysicalCustomer;
j'ai pas bien compris !!!!

2017-07-30 00:00 UTC, RCv20617ma commented on app/Resources/translations/messages.fr.yml
> +reference_gender_.MALE: Masculin
Oui je sais, il seront accessible

2017-07-30 00:00 UTC, aka-men commented on src/CustomerBundle/Entity/AbstractCustomer.php
> +    abstract public function fullName();
ok

2017-07-30 00:00 UTC, RCv20617ma commented on app/Resources/translations/messages.fr.yml
> +reference_gender_.MALE: Masculin
il vaut mieux qu'on regroupe ca par bundle

2017-07-30 00:00 UTC, RCv20617ma commented on app/Resources/views/layout.html.twig
> +{% block pluginsJavascript %}{% endblock %}
oui pour separer les resource js et css

2017-07-30 00:00 UTC, aka-men commented on src/CustomerBundle/Entity/AbstractCustomer.php
> +        $mainEmail = $this->getEmails()->isEmpty() ? null : $this->getEmails()->first()->getEmail();
ok

2017-07-30 00:01 UTC, aka-men commented on src/CustomerBundle/Entity/AbstractCustomer.php
> +                $mainEmail = $ec->getEmail();
ok

2017-07-30 15:05 UTC, merged